### ISSUE TITLE
Khung nội dung cho 1.3, 1.4, 1.5

### ISSUE THREAD

**Issue by riverspart** [riverspart/uet-adv-sw-engineering#2]
ALo, Minh ơi mày tạo khung nội dung cho 1.3, 1.4, 1.5 luôn nhé chưa cần nội dung đâu để mình release khung nội dung cho slide nhé. 
Nhanh nhanh, mai release khung nội dung nhé!!!

**Comment by riverspart** [comment]
lấy template ở bản 1.0 luôn nhé!!

**Comment by hcminh225** [comment]
oki

**Comment by riverspart** [comment]
Cố gắng hôm nay deadline cho khung slide nhé. Mai hoàn thành nội dung. ko có thì ko kịp đấy.
