### ISSUE TITLE
Khung nội dung cho 1.6, 1.7, 1.8

### ISSUE THREAD

**Issue by riverspart** [riverspart/uet-adv-sw-engineering#3]
ALo, Tùng ơi mày tạo khung nội dung cho 1.6, 1.7, 1.8 luôn nhé chưa cần nội dung đâu để mình release khung nội dung cho slide nhé. 
Nhanh nhanh, mai release khung nội dung nhé!!!

**Comment by riverspart** [comment]
lấy template ở bản 1.0 luôn nhé!!

**Comment by hcminh225** [comment]
oki sau. Bọn mình tổng hợp dần lên wiki nhé

**Comment by riverspart** [comment]
cái wiki để sau. giờ cậu lấy latest của nhánh master về merge của c vào rồi commit lên. cứ có khung các phần đã. nội dung update tiếp. để tớ tạo xương tiêu đề cho wiki cho. cả file pptx và txt nhé

**Comment by tungnt11191** [comment]
Hẹn ae 11h về làm. Đang đi công chuyện

**Comment by riverspart** [comment]
Nhanh lên mày, để hôm nay release cái khung cho slide cái. cố gắng 2h tao release khung slide nhé

**Comment by tungnt11191** [comment]
Done
